name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --exclude=".git*" --exclude=".github" --exclude=".env" --exclude="node_modules" --exclude="vendor" --exclude="upload"
          path: ./
          remote_path: ${{ secrets.HOSTINGER_TARGET_DIR }}
          remote_host: ${{ secrets.HOSTINGER_HOST }}
          remote_user: ${{ secrets.HOSTINGER_USERNAME }}
          remote_port: ${{ secrets.HOSTINGER_PORT }}
          remote_key: ${{ secrets.HOSTINGER_SSH_KEY }}
